### ISSUE TITLE
Gridview Update after update select value 

### ISSUE THREAD

**Issue by MilanNSuthar** [yii2mod/yii2-editable#3]
Gridview Update after update select value  not working

**Comment by igor-chepurnoi** [comment]
Can you please describe more detail your issue?

**Comment by MilanNSuthar** [comment]
`[
  'header' => DidmasterModule::t('didmaster', 'Service'),
  'class' => EditableColumn::className(),
  'attribute' => 'serviceName.serv_name',
  'url' => '/didmaster/didtenant/get-services',
  'type' => 'select',
  'editableOptions' => function ($model) {
           return [
                      'source' => ArrayHelper::map(ServiceMaster::getServicePackages(), 'serv_id', 'serv_name'),
                      'value' => $model->sv_id,
                                    ];
    },
],`

Above is my code.
When I called 'get-services()' method and get complete operation with success, I need to reload my Grid.

**Comment by igor-chepurnoi** [comment]
Ok, I check it later

**Comment by MilanNSuthar** [comment]
@igor-chepurnoi are you understand my problem?

**Comment by igor-chepurnoi** [comment]
Yes, As I understand, you need to reload gridview after value has been saved, right?

**Comment by MilanNSuthar** [comment]
@igor-chepurnoi Yes, I need to reload gridview after value has been saved. Please help me in it.
Thanking you.

**Comment by igor-chepurnoi** [comment]
Ok, I'll try to help.

**Comment by igor-chepurnoi** [comment]
I have updated this package, please update the package to `dev-master` version, and use the following code for update your gridview

Grid view example
```php
<?php Pjax::begin(['timeout' => 10000, 'options' => ['id' => 'grid-pjax-container']]); ?>
    <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => EditableColumn::class,
                'attribute' => 'username',
                'url' => ['edit-user'],
                'clientOptions' => [
                    'success' => (new \yii\web\JsExpression('function() {
                        $.pjax.reload({container: "#grid-pjax-container"}); // this code for update grid
                    }'))
                ],
            ],
            [
                'header' => Yii::t('app', 'Action'),
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
            ],
        ],
    ]);
    ?>
    <?php Pjax::end(); ?>
```

**Comment by MilanNSuthar** [comment]
@igor-chepurnoi  its giving  following exception
 Setting unknown property: yii2mod\editable\EditableColumn::clientOptions

**Comment by igor-chepurnoi** [comment]
You need to update yii2mod/yii2-editable package via composer update

**Comment by MilanNSuthar** [comment]
Thanks @igor-chepurnoi .
