### ISSUE TITLE
How to add multiple attributes in email type

### ISSUE THREAD

**Issue by MilanNSuthar** [yii2mod/yii2-editable#9]
@igor-chepurnoi 
 How can I add multiple= 'true' in email type. ?
Actually Html5 has multiple attributes to enter multiple email address with validation.

**Comment by igor-chepurnoi** [comment]
Hi, try the following code in your grid column

```php
'options' => ['multiple' => true],
```

**Comment by MilanNSuthar** [comment]
Thanks
